---
title: "Preliminary Report"
author: "Jillian Shao"
date: "2023-01-12"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include = FALSE}
library(filterTD)
library(dplyr)
library(scales)
library(knitr)
```

## Basic Summary of All Data
``` {r include = FALSE}
Metadata = "C:/Users/shaoj/Documents/GitHub/filterTD/extdata/dummy_sync.csv"
metadata <- read.table(file = Metadata, header=TRUE, sep=";")

animal_tag_data <- data.frame(tags_subset[1])
sync_tag_data <- data.frame(tags_subset[2])
ref_tag_data <- data.frame(tags_subset[3])

# Merge animal tag data and animal metadata 
animal_merged <- merge(animal_tag_data, metadata, by = id_col_name)
```

``` {r echo = FALSE}
# Number of observations and animal tags
stats <- num.obs.per.tag(animal_tag_data, id_col_name, graph=FALSE)
```

``` {r echo = FALSE, results = 'asis'}
cat("Total number of observations:", stats[1], " \n")
cat("Total number of animal tags", stats[2], " \n")
```

## Basic Summary of Each Animal
``` {r echo = FALSE, results = 'asis'}
# Number of observations and tags for each animal
for(x in vec_species) {
        cat("### Graph for", x, " \n")
        num_obs_per_tag_ani <- num.obs.per.tag(animal_merged, id_col_name, graph=TRUE,
                                               grouping=x,
                                               grouping_col_name=sp_col_name,
                                               metadata=metadata)
        cat("Total number of observations for", x, ": ", num_obs_per_tag_ani[1], " \n")
        cat("Total number of tags for", x, ": ", num_obs_per_tag_ani[2], " \n")
        cat("\n")
}
```

## Understanding HPE Quantiles
Given the percentages of data to keep (0.95, 0.9, 0.75, 0.5, and 0.25), below is 
graph of HPE vs HPEm at each quantile and the HPE value, in column 'x', to retain the given
percentage of data. 
``` {r echo = FALSE}
sync_hpe <- hpe.quantiles(sync_tag_data, hpe_col_name, hpem_col_name)
kable(sync_hpe)
```

``` {r echo = FALSE}
# Take sync_hpe output as vector
sync_hpe_vec <- as.vector(unname(sync_hpe))
# Testing sync tags summary (with HPE)
sync_summary <- sync.summary(sync_tag_data, hpe_col_name, sync_hpe_vec)
kable(sync_summary) 
```

## Graph of Detections per Receiver (Sync Tags)
``` {r echo = FALSE, results = 'asis', fig.width=10, fig.height=10, fig.fullwidth=TRUE, warning = FALSE}
receiver.detections(sync_tags=sync_tag_data, sync_hpe_col_name=hpe_col_name,
                    lat_col_name=lat_col_name, long_col_name=long_col_name, id_col_name=id_col_name)
```

## Graph of Detections per Receiver (Sync Tags) for HPE <= 250
```{r include = FALSE}
sync_tag_data_250 <- subset(sync_tag_data, HPE<=250)
```

``` {r echo = FALSE, results = 'asis', fig.width=10, fig.height=10, fig.fullwidth=TRUE, warning = FALSE}
receiver.detections(sync_tags=sync_tag_data_250, sync_hpe_col_name=hpe_col_name,
                    lat_col_name=lat_col_name, long_col_name=long_col_name, id_col_name=id_col_name)
```

## Graphs of Animal Positions
``` {r echo = FALSE, results = 'asis'}
for(x in ani_tags) {
  cat("### Graph for", x, " \n")
  animal.positions(animal_tags=animal_tag_data, ani_hpe_col_name=hpe_col_name,
                   lat_col_name=lat_col_name, long_col_name=long_col_name,
                   num_bins=num_bins, ID=x, id_col_name=id_col_name)
  cat(" \n")
}
```

